### ISSUE TITLE
How do I know it is using OpenAI?

### ISSUE THREAD

**Issue by europacafe** [SecureAI-Tools/SecureAI-Tools#25]
I have an OpenAI api (secret) key and uncomment, in .env file, two lines
```
https://github.com/SecureAI-Tools/SecureAI-Tools/blob/main/lib/types/core/model-provider-config.ts
MODEL_PROVIDER_CONFIGS='[{"type":"OPENAI","apiBaseUrl":"https://api.openai.com/v1","apiKey":"sk-4Uh......k3i"}]
```
How do I know it is using OpenAI to find answer for my query?
Should I delete the Mistral model I installed in version 0.0.0? If yes, what is the proper way to remove it?
Thanks.

**Comment by europacafe** [comment]
Thanks.
I can't pull OpenAI model.
![image](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/51871976/e68e3e78-403b-474d-a84c-bcdbc65c1b65)

**Comment by JayNakrani** [comment]
Ah, you need to upgrade to v0.0.1 first -- the v0.0.0 does not support OpenAI models. See the Upgrading section at https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.1

**Comment by europacafe** [comment]
I already upgraded it. That's why the auto-created .env file has the commented OpenAI lines which I had uncommented as stated above.
How do I check the version I'm running? I checked the log file and didn't see any indication.

**Comment by JayNakrani** [comment]
@europacafe The screenshot says it's on `v0.0.0` because the latest version has one more field for model-type in that form. To make sure you get the latest version, can you change the tag in docker-compose from `latest` to `v0.0.1`? That will force it to download `v0.0.1` (although I don't understand why the tag `latest` didn't work in your case -- may be some caching issue).

**Comment by europacafe** [comment]
Thanks. Specifying v0.0.1 does work.
Could you recommend LLM name? I'm not a paid user.
