### ISSUE TITLE
docker compose up - prisma error

### ISSUE THREAD

**Issue by shuther** [SecureAI-Tools/SecureAI-Tools#40]
I am getting the error below after `docker compose up`, while I have never been able to login. As a fix, I changed the name of the DB and it fixed the problem but maybe there is another issue?

```
deployment-web-1        | No pending migrations to apply.
deployment-web-1        | Seeding database ...
deployment-vector-db-1  | Collecting numpy
deployment-vector-db-1  |   Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
deployment-web-1        | PrismaClientKnownRequestError: 
deployment-web-1        | Invalid `prisma.user.create()` invocation:
deployment-web-1        | 
deployment-web-1        | 
deployment-web-1        | Unique constraint failed on the fields: (`email`)
deployment-web-1        |     at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6730)
deployment-web-1        |     at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
deployment-web-1        |     at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
deployment-web-1        |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
deployment-web-1        |     at async file:///app/tools/db-seed.mjs:18:29
deployment-web-1        |     at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:128:8426)
deployment-web-1        |     at async main (file:///app/tools/db-seed.mjs:16:5) {
deployment-web-1        |   code: 'P2002',
deployment-web-1        |   clientVersion: '5.3.1',
deployment-web-1        |   meta: { target: [ 'email' ] }
```

**Comment by JayNakrani** [comment]
> deployment-web-1 
> ...
> deployment-vector-db-1

@shuther Looks like you are running code from the main branch directly -- i.e. using `deployment/docker-compose.yml` file directly at HEAD on main branch. The main branch is unstable right now because we are doing a large refactor.

Please use the released version: https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.1. Released versions of the file should be stable. Please follow the installation instructions at https://github.com/SecureAI-Tools/SecureAI-Tools?tab=readme-ov-file#docker-compose-recommended -- it uses the released versions of docker-compose and env file etc.

**Comment by JayNakrani** [comment]
@shuther These issues should be resolved now. Please try the latest release ([v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3)) by following [installation instructions](https://github.com/SecureAI-Tools/SecureAI-Tools/#install) and let me know if you run into issues. I'm closing this issue for now, but ping me if you need any help.
